<a href="https://colab.research.google.com/github/Lekanville/AI-Traffic-Control-System/blob/julius/TCS_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from numpy import save
from numpy import load
import matplotlib.pyplot as plt

In [2]:
from numpy import save
from numpy import load

In [3]:
data = load('drive/MyDrive/Colab_Notebooks/AI_Traffic_Control_System/data.npy')
labels = load('drive/MyDrive/Colab_Notebooks/AI_Traffic_Control_System/labels.npy')

In [4]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import BatchNormalization
from keras.layers import Conv2D
from keras.layers import Activation
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import Input
from keras.layers import MaxPooling2D
from keras.models import Model
from keras.optimizers import RMSprop
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = data

In [7]:
X = X.reshape(-1, 256, 256, 1)

In [8]:
X.shape

(360, 256, 256, 1)

In [9]:
y = []
for i in labels:
    if i == 1:
        ts = [1.0, 0.0, 0.0, 0.0]
    elif i ==2:
        ts = [0.0, 1.0, 0.0, 0.0]
    elif i ==3:
        ts = [0.0, 0.0, 1.0, 0.0]
    elif i ==4:
        ts = [0.0, 0.0, 0.0, 1.0]
    y.append(ts)
y = np.asarray(y, dtype=np.float32)
y

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], dtype=float32)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=101)

In [11]:
print(X_train.shape)
print(X_test.shape)

(324, 256, 256, 1)
(36, 256, 256, 1)


In [12]:
print(y_train.shape)
print(y_test.shape)

(324, 4)
(36, 4)


In [13]:
model = Sequential()

model.add(Conv2D(16,(5,5),padding='same',input_shape = (256, 256, 1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding = 'same'))
#model.add(Dropout(0.4))

model.add(Conv2D(32,(5,5),padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding = 'same'))
#model.add(Dropout(0.6))

model.add(Conv2D(64,(5,5),padding='same'))
model.add(Activation('relu'))
#model.add(Dropout(0.8))

model.add(Flatten())
model.add(Dense(4))
model.add(Activation('softmax'))

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 256, 256, 16)      416       
_________________________________________________________________
activation (Activation)      (None, 256, 256, 16)      0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 128, 128, 16)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 128, 128, 32)      12832     
_________________________________________________________________
activation_1 (Activation)    (None, 128, 128, 32)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 64, 64, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 64, 64, 64)        5

In [16]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
                   
model.fit(X_train, y_train, epochs=100, batch_size=100, verbose=300)

Epoch 1/100
Epoch 2/100
Epoch 3/100
Epoch 4/100
Epoch 5/100
Epoch 6/100
Epoch 7/100
Epoch 8/100
Epoch 9/100
Epoch 10/100
Epoch 11/100
Epoch 12/100
Epoch 13/100
Epoch 14/100
Epoch 15/100
Epoch 16/100
Epoch 17/100
Epoch 18/100
Epoch 19/100
Epoch 20/100
Epoch 21/100
Epoch 22/100
Epoch 23/100
Epoch 24/100
Epoch 25/100
Epoch 26/100
Epoch 27/100
Epoch 28/100
Epoch 29/100
Epoch 30/100
Epoch 31/100
Epoch 32/100
Epoch 33/100
Epoch 34/100
Epoch 35/100
Epoch 36/100
Epoch 37/100
Epoch 38/100
Epoch 39/100
Epoch 40/100
Epoch 41/100
Epoch 42/100
Epoch 43/100
Epoch 44/100
Epoch 45/100
Epoch 46/100
Epoch 47/100
Epoch 48/100
Epoch 49/100
Epoch 50/100
Epoch 51/100
Epoch 52/100
Epoch 53/100
Epoch 54/100
Epoch 55/100
Epoch 56/100
Epoch 57/100
Epoch 58/100
Epoch 59/100
Epoch 60/100
Epoch 61/100
Epoch 62/100
Epoch 63/100
Epoch 64/100
Epoch 65/100
Epoch 66/100
Epoch 67/100
Epoch 68/100
Epoch 69/100
Epoch 70/100
Epoch 71/100
Epoch 72/100
Epoch 73/100
Epoch 74/100
Epoch 75/100
Epoch 76/100
Epoch 77/100
Epoch 78

In [18]:
y_pred = np.argmax(model.predict(X_test), axis=-1)

In [19]:
print(confusion_matrix(np.argmax(y_test, axis = 1), y_pred))
print('\n')
print(classification_report(np.argmax(y_test, axis = 1), y_pred))

[[12  0  0  0]
 [ 0  9  0  1]
 [ 0  0  8  1]
 [ 1  0  0  4]]


              precision    recall  f1-score   support

           0       0.92      1.00      0.96        12
           1       1.00      0.90      0.95        10
           2       1.00      0.89      0.94         9
           3       0.67      0.80      0.73         5

    accuracy                           0.92        36
   macro avg       0.90      0.90      0.89        36
weighted avg       0.93      0.92      0.92        36

